from langchain_openai import ChatOpenAI
import os
import sys
import glob
import time
import importlib
import asyncio
from typing import List, Any
from pydantic import BaseModel, Field
import pandas as pd
from dotenv import load_dotenv
from langgraph.graph import StateGraph, START, END, MessagesState
from langchain_core.messages import HumanMessage

load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# =====================================================================
# 1. GRAPH STATE DEFINITION
# =====================================================================
class NormalizationState(MessagesState):
    folder_path: str                # Target incoming parsed directory (e.g. 'parsed_csvs')
    path_list: List[str]            # Queue of pending parsed CSV file paths 
    file_path: str                  # The CSV path currently being processed
    df_summary: dict                # Sampled structural/data-type summary of current CSV
    generated_code: str             # Code generated by the model
    retry_count: int                # Failure retry counter for current CSV
    error_message: str              # Failure runtime trace or success flag

# =====================================================================
# 2. DISCOVERY & ROUTING NODES
# =====================================================================
async def get_csv_paths(state: NormalizationState):
    """
    Scans the provided 'folder_path' for parsed CSVs and normalizes paths.
    """
    search_pattern = os.path.join(state['folder_path'], "*.csv")
    path_list = [os.path.normpath(p) for p in glob.glob(search_pattern)]
    print(f"[Discovery] Found {len(path_list)} CSV file(s) in '{state['folder_path']}'")
    return {"path_list": path_list}


async def process_next_file(state: NormalizationState):
    """
    Pops the next file out of the pipeline queue and clears transient variables.
    """
    paths = state.get("path_list", []).copy()
    
    if not paths:
        return {"file_path": ""}
    
    next_file = paths.pop(0)
    print(f"\n[Orchestrator] Starting normalization loop for: {next_file}")
    
    return {
        "path_list": paths,
        "file_path": next_file,
        "retry_count": 0,
        "error_message": "",
        "generated_code": "",
        "df_summary": {}
    }

# =====================================================================
# 3. TRANSFORMATION COMPONENT NODES
# =====================================================================
async def inspect_data(state: NormalizationState):
    """Loads CSV slice and extracts schema metadata profile for the LLM."""
    df = pd.read_csv(state['file_path'])
    
    # Safely generate sample row records (handle small or empty datasets)
    sample_count = min(2, len(df))
    samples = df.sample(sample_count).to_dict(orient='records') if sample_count > 0 else []
    
    summary = {
        "columns": list(df.columns),
        "dtypes": df.dtypes.astype(str).to_dict(),
        "samples": samples
    }
    return {"df_summary": summary}


class FunctionSchema(BaseModel):
    function: str = Field(
        description="The complete, entire executable Python function code for `normalize_data(df)`. This must include the function definition `def normalize_data(df):`, the full logical body using Pandas, and the return statement. Do not just return the function name."
    )

llm = ChatOpenAI(model="gpt-4.1-mini").with_structured_output(FunctionSchema)


async def generate_code(state: NormalizationState):
    """LLM writes the specialized Python normalization schema function."""
    error_context = ""
    if state.get("error_message"):
        error_context = f"""
### PREVIOUS ERROR ENCOUNTERED:
The last version of your function failed with the following error/issue:
{state["error_message"]}

Here is your previous function logic:
{state["generated_code"]}

Please analyze the profile and errors again, and fix the code logic.
"""
        
    prompt = f"""
You are an expert Senior Data Engineer specializing in Security Operations (SecOps) Telemetry.
I have a parsed vulnerability scanner CSV file. 

### INPUT DATA PROFILE:
{state["df_summary"]}

### TASK:
Write a Python function `normalize_data(df)` using Pandas that transforms this raw data into our "Zero-Touch" standardized schema.

### TARGET SCHEMA columns to ensure:
- **vuln_id**: Use CVE ID if present. Fallback to scanner-specific ID. If both missing, use None.
- **severity_raw**: The original severity string, converted to ALL UPPERCASE (e.g., 'high' -> 'HIGH').
- **ip**: The IP Address or null.
- **hostname**: hostname or null.
- **port**: The port number or null.
- **instance_id**: cloud instance id or null.
- **component**: The package or software name.
- **affected_version**: The version of the component.
- **cvss_score**: Float. (Extract from string if necessary).
- **cvss_vector**: String representation of CVSS vector.
- **description**: Summary of the vulnerability.
- **references**: MUST BE A LIST of strings. (If source is a comma/newline string, split it).
- **fixed_version**: The version where the vulnerability is patched/fixed. If not available, use null.

### CRITICAL CONSTRAINTS:
1. Handle Missing Columns: If a column needed for the schema doesn't exist in the input, initialize it with `None` or appropriate defaults.
2. Handle Nested Lists: Ensure the 'references' column in the output is a standard Python list for every row.
3. Robustness: Use `.get()` or `np.where()` logic to avoid `KeyError` if a column name varies.

### OUTPUT format:
Return ONLY the executable code for the function `normalize_data(df)`. No descriptions or formatting markdown cells.

{error_context}
"""
    # Updated to ainvoke for async execution
    response = await llm.ainvoke([HumanMessage(content=prompt)])
    code = response.function.replace("```python", "").replace("```", "").strip()
    return {"generated_code": code, "retry_count": state["retry_count"] + 1}


async def save_generated_code(state: NormalizationState):
    with open("generated_normalization_func.py", "w") as f:
        f.write(state["generated_code"])
    return {}


async def execute_generated_code(state: NormalizationState):
    """
    Executes code dynamically. If successful, creates 'normalized_csvs',
    appends '_normalized' to the original filename, and stores it directly.
    """
    try:
        spec = importlib.util.spec_from_file_location("dynamic_mod", "generated_normalization_func.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        # Execute transformation 
        raw_df = pd.read_csv(state["file_path"])
        df = module.normalize_data(raw_df)
        
        if df is None or df.empty:
            return {"error_message": "Execution finished successfully, but returned an EMPTY DataFrame."}
        
        # Immediate Save Routine (Zero dataframes retained inside state memory)
        output_dir = os.path.join(BACKEND_DIR, "normalized_output")
        os.makedirs(output_dir, exist_ok=True)
        
        original_basename = os.path.basename(state["file_path"])       
        name_without_ext, _ = os.path.splitext(original_basename)       
        output_filename = f"{name_without_ext}_normalized.csv"          
        
        full_output_path = os.path.join(output_dir, output_filename)
        df.to_csv(full_output_path, index=False)
        print(f"[Success] Exported Normalized Output: {full_output_path}")
        
        return {"error_message": "SUCCESS"}

    except Exception as e:
        return {"error_message": f"Runtime Transformation Error: {str(e)}"}

# =====================================================================
# 4. FINAL CONSOLIDATION CONCAT NODE
# =====================================================================
async def merge_normalized_csvs(state: NormalizationState):
    """
    Executes right before END. Combines all processed files from 
    'normalized_output/' folder into a single unified 'working.csv'.
    """
    target_dir = os.path.join(BACKEND_DIR, "normalized_output")
    search_pattern = os.path.join(target_dir, "*_normalized.csv")
    normalized_files = glob.glob(search_pattern)
    
    if not normalized_files:
        print("[Consolidation] No normalized data found to compile.")
        return {}
        
    print(f"\n[Consolidation] Compiling {len(normalized_files)} telemetry sets into single log...")
    
    df_list = [pd.read_csv(f) for f in normalized_files]
    working_df = pd.concat(df_list, ignore_index=True)
    
    output_path = os.path.join(target_dir, "working.csv")
    working_df.to_csv(output_path, index=False)
    print(f"[Consolidation Success] Created unified matrix file at: {output_path}")
    return {}

# =====================================================================
# 5. CONDITIONS & ROUTING LOGIC
# =====================================================================
async def route_after_orchestrator(state: NormalizationState):
    if not state.get("file_path"):
        print("\n[Orchestrator] Loop processing complete. Transitioning to terminal data merge.")
        return "Merge Matrix"
    return "Process File"


async def should_retry(state: NormalizationState):
    if state.get("error_message") == "SUCCESS":
        return "Next File / Limit Reached"
    
    # Add this print statement to debug the actual code failure!
    print(f"[Validation Failure] {state.get('error_message')}")
    
    if state.get("retry_count", 0) >= 3:
        print(f"Max validation cycles reached for {state['file_path']}. Skipping.")
        return "Next File / Limit Reached"
    return "Validation Failed"

# =====================================================================
# 6. ARCHITECTURE GRAPH WRAPPING & WIRING
# =====================================================================
def build_normalization_graph():
    graph = StateGraph(NormalizationState)

    # Append Nodes
    graph.add_node("get_csv_paths", get_csv_paths)
    graph.add_node("process_next_file", process_next_file)
    graph.add_node("inspect_data", inspect_data)
    graph.add_node("generate_code", generate_code)
    graph.add_node("save_generated_code", save_generated_code)
    graph.add_node("execute_generated_code", execute_generated_code)
    graph.add_node("merge_normalized_csvs", merge_normalized_csvs)

    # Pipeline Start & Flow Wiring
    graph.add_edge(START, "get_csv_paths")
    graph.add_edge("get_csv_paths", "process_next_file")

    graph.add_conditional_edges(
        "process_next_file",
        route_after_orchestrator,
        {
            "Merge Matrix": "merge_normalized_csvs",
            "Process File": "inspect_data"
        }
    )

    graph.add_edge("inspect_data", "generate_code")
    graph.add_edge("generate_code", "save_generated_code")
    graph.add_edge("save_generated_code", "execute_generated_code")

    # Routing Loopback Engine 
    graph.add_conditional_edges(
        "execute_generated_code", 
        should_retry, 
        {
            "Next File / Limit Reached": "process_next_file", 
            "Validation Failed": "generate_code"
        }
    )

    # Connect Consolidation Node straight to standard Workflow Termination
    graph.add_edge("merge_normalized_csvs", END)

    workflow = graph.compile()
    return workflow