from langchain_openai import ChatOpenAI
import os
import sys
import json
import chardet
import importlib
from typing import Any, List
from pydantic import BaseModel
import pandas as pd
from dotenv import load_dotenv
import glob

from langgraph.graph import StateGraph, START, END, MessagesState
from langchain_core.messages import HumanMessage

load_dotenv()

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# =====================================================================
# 1. GRAPH STATE DEFINITION
# =====================================================================
class GraphState(MessagesState):
    folder_path: str
    path_list: List[str]            # Queue of pending raw data file paths
    file_path: str                  # The file path currently being processed
    parse_code_file_path: str       # Temporary script file generated by LLM
    raw_data: dict                  # Memory-loaded JSON data of current file
    scanner_schema_info: dict       # Inferred structural metadata of current file
    function: str                   # Code generated by the model
    retry_count: int                # Failure retry counter for current file
    error_message: str              # Failure runtime trace or success flag

# =====================================================================
# 2. ORCHESTRATION / ROUTING NODE
# =====================================================================
async def process_next_file(state: GraphState):
    """
    Acts as the entry and traffic router. Pops the next file out of 
    the pipeline queue and clears transient variables for the fresh loop.
    """
    paths = state.get("path_list", []).copy()
    
    if not paths:
        return {"file_path": ""}
    
    # Pop the first file to be executed
    next_file = paths.pop(0)
    print(f"\n[Orchestrator] Starting processing loop for: {next_file}")
    
    return {
        "path_list": paths,
        "file_path": next_file,
        "retry_count": 0,
        "error_message": "",
        "function": "",
        "raw_data": {},
        "scanner_schema_info": {}
    }

# =====================================================================
# 3. COMPONENT NODES
# =====================================================================
async def get_file_paths(state: GraphState):
    search_pattern = os.path.join(state['folder_path'], "*.json")
    path_list = [os.path.normpath(path) for path in glob.glob(search_pattern)]
    print(f"[Discovery] Found {len(path_list)} file(s) in '{state['folder_path']}'")
    return {"path_list": path_list}

async def load_json(state: GraphState):
    with open(state["file_path"], 'rb') as f:
        raw_bytes = f.read()
        result = chardet.detect(raw_bytes)
        encoding = result['encoding']
    
    data = json.loads(raw_bytes.decode(encoding))
    return {"raw_data": data}


def extract_internal_structure(data, path="", depth=0, max_depth=5):
    """Kept synchronous as it is a CPU-bound recursive helper."""
    if depth > max_depth:
        return "..."
    if isinstance(data, dict):
        structure = {}
        for key, value in data.items():
            structure[key] = extract_internal_structure(value, f"{path}.{key}", depth + 1)
        return structure
    elif isinstance(data, list):
        if len(data) == 0:
            return []
        list_sample = extract_internal_structure(data[0], f"{path}[0]", depth + 1)
        return [f"Array(size={len(data)})", list_sample]
    else:
        return f"{type(data).__name__} (e.g., {str(data)[:30]})"


async def process_scanner_output(state: GraphState):
    structure_map = extract_internal_structure(state["raw_data"])
    entry_points = []
    if isinstance(state["raw_data"], dict):
        for k, v in state["raw_data"].items():
            if isinstance(v, list) and len(v) > 0:
                entry_points.append(k)

    scanner_schema_info = {
        "detected_entry_points": entry_points,
        "schema_map": structure_map
    }
    return {"scanner_schema_info": scanner_schema_info}


class ParseFunction(BaseModel):
    function_name: str
    function: str

llm = ChatOpenAI(model="gpt-4.1-mini").with_structured_output(ParseFunction)


async def generate_parse_code(state: GraphState):
    error_context = ""
    if state.get("error_message"):
        error_context = f"""
### PREVIOUS ERROR ENCOUNTERED:
The last version of the function failed with the following error/issue:
{state["error_message"]}

Here is the last version of the function:
{state["function"]}

Please analyze the metadata again and fix the logic to ensure data is correctly extracted.
"""
        
    message = f"""
You are an expert AIOps Developer and Data Engineer specializing in automated security telemetry normalization.

### CONTEXT:
I am building a "Zero-Touch" vulnerability remediation pipeline. I have already analyzed a security scanner's output and extracted its structural metadata.

### INPUT METADATA:
{state["scanner_schema_info"]}

### TASK:
Write a Python function `flatten_vulnerabilities_to_df(scan_output)` that flattens the vulnerability data into a pandas DataFrame.

### CONSTRAINTS & LOGIC:
1. DATA LOCATION: Do not look for 'detected_entry_points' inside the 'scan_output'. Instead, use the value(s) provided in the METADATA above to know which keys in 'scan_output' contain the vulnerability data.
2. BRANCHING LOGIC:
   - If the metadata indicates vulnerabilities are nested within a list of groups (e.g., Trivy 'Results' -> 'Vulnerabilities'), you MUST loop through the groups and concatenate the flattened results.
   - If the metadata indicates a direct list (e.g., Snyk 'vulnerabilities' or Grype 'matches'), you MUST pass the entire list to pd.json_normalize() in one vectorized call.
3. ZERO-TOUCH EXTRACTION: Use pd.json_normalize(sep='.') to ensure every nested field (e.g., CVSS scores, identifiers) becomes a separate column. Do not manually select or hardcode column names.
4. DEFENSIVE CODING: Return an empty DataFrame if the target keys are missing or the lists are empty.

### OUTPUT:
Provide only the Python function. No conversational filler.

{error_context}
"""
    # Updated to ainvoke for async compatibility
    result = await llm.ainvoke([HumanMessage(content=message)])
    return {"function": result.function, "retry_count": state["retry_count"] + 1}


async def save_parse_code(state: GraphState):
    with open(state["parse_code_file_path"], "w") as f:
        f.write(state["function"])
    return {}


async def execute_parse_code(state: GraphState):
    """
    Executes code dynamically. If successful, creates the 'parsed_csvs' 
    directory, immediately dumps the DataFrame to the CSV, and avoids saving it to state.
    """
    try:
        spec = importlib.util.spec_from_file_location("dynamic_mod", state["parse_code_file_path"])
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        
        df = module.flatten_vulnerabilities_to_df(state["raw_data"])
        
        if df is None or df.empty:
            return {
                "error_message": "Execution successful, but the resulting DataFrame is EMPTY. Ensure you are targeting the correct nested keys."
            }
        
        # Immediate Save Routine (No dataframe kept in state context)
        output_dir = os.path.join(BACKEND_DIR, "parsed_csvs")
        os.makedirs(output_dir, exist_ok=True)
        
        original_basename = os.path.basename(state["file_path"]) 
        name_without_ext, _ = os.path.splitext(original_basename) 
        output_filename = f"{name_without_ext}_parsed.csv"        
        
        full_output_path = os.path.join(output_dir, output_filename)
        df.to_csv(full_output_path, index=False)
        print(f"[Success] Exported: {full_output_path}")
        
        return {"error_message": "SUCCESS"}

    except Exception as e:
        return {
            "error_message": f"Runtime Error: {str(e)}"
        }

# =====================================================================
# 4. CONDITIONAL ROUTERS
# =====================================================================
def route_after_orchestrator(state: GraphState):
    """Determines whether to execute the popped path or exit if queue is empty."""
    if not state.get("file_path"):
        print("\n[Orchestrator] All files processed successfully. Exiting workflow.")
        return "Exit Pipeline"
    return "Process File"


def should_retry(state: GraphState):
    """
    Evaluates current execution. If it succeeds or hits the failure ceiling, 
    routes back to process_next_file rather than killing the entire graph.
    """
    if state.get("error_message") == "SUCCESS":
        return "Next File / Limit Reached"
    
    if state.get("retry_count", 0) >= 3:
        print(f"Max retries reached for {state['file_path']}. Skipping to next input.")
        return "Next File / Limit Reached"
    
    print(f"Validation failed: {state['error_message']}. Retrying code generation...")
    return "Validation Failed"

# =====================================================================
# 5. STATE GRAPH ARCHITECTURE DEFINITION
# =====================================================================
def build_parsing_graph():
    graph = StateGraph(GraphState)
    # Add Nodes
    graph.add_node("get_file_paths", get_file_paths)
    graph.add_node("process_next_file", process_next_file)
    graph.add_node("load_scanner_output", load_json)
    graph.add_node("get_schema_structure", process_scanner_output)
    graph.add_node("generate_parse_code", generate_parse_code)
    graph.add_node("save_parse_code", save_parse_code)
    graph.add_node("execute_parse_code_and_validate_execution", execute_parse_code)

    # Orchestrator Workflow Wiring
    graph.add_edge(START, "get_file_paths")
    graph.add_edge("get_file_paths", "process_next_file")

    graph.add_conditional_edges(
        "process_next_file",
        route_after_orchestrator,
        {
            "Exit Pipeline": END,
            "Process File": "load_scanner_output"
        }
    )

    graph.add_edge("load_scanner_output", "get_schema_structure")
    graph.add_edge("get_schema_structure", "generate_parse_code")
    graph.add_edge("generate_parse_code", "save_parse_code")
    graph.add_edge("save_parse_code", "execute_parse_code_and_validate_execution")

    # Context Correction Loop & Sequential Step Up
    graph.add_conditional_edges(
        "execute_parse_code_and_validate_execution", 
        should_retry, 
        {
            "Next File / Limit Reached": "process_next_file", 
            "Validation Failed": "generate_parse_code"
        }
    )

    workflow = graph.compile()
    return workflow